### ISSUE TITLE
<br><br> in je code is lastig opnieuw te her-stylen met CSS. Probeer het aantal <br> elementen te beperken

### ISSUE THREAD

**Issue by JeroenHeemskerk** [quincy-tromp/educom-webshop-basis#16]
In de code hieronder staan veel `<br>` elementen die alleen voor styling worden gebruikt,
https://github.com/quincy-tromp/educom-webshop-basis/blob/649864ec1101937ffb87894b3129209225925b6b/contact.html#L29-L51

Het is beter om bijv. een `<input>` en een `<label>` in een `<div>` te zetten om te zorgen dat het veld erna op de volgende regel komt, je kan dan in je CSS besluiten of deze op een nieuwe regel komt voor kleine schermen en naast elkaar voor grotere schermen of zoiets. Het is dan meer flexibel. 

Gebruik `<br>` alleen in paragraven om aan te geven dat de volgende zin op een nieuwe regel begint.

Je kan dan ook gelijk deze `<div>` gebruiken om de styling aan te hangen in plaats dat je ieder label en iedere input/select/textarea een class geeft.

HTML: 
```HTML
 <div class="form_group">
    <label for="name">Name</label> 
    <input type="text" id="name" name="name">
 </div>
```
CSS
```CSS
.form_group {
    display: block;
}
.form_group label {
    display: inline-block;
    width: 50px;
    text-align: left;
}
.form_group input, .form_group select, .form_group textarea {
    background-color: #DDE6ED;
    margin-left: 12px;
    width: 400px;
}
```
